### ISSUE TITLE
Enable master branch protection on all org level repositories

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-common#295]
- [ ] [.github](https://github.com/googleapis/.github/issues/2)
- [ ] [aip](https://github.com/googleapis/aip/issues/551)
- [ ] [api-common-java](https://github.com/googleapis/api-common-java/issues/166)
- [ ] [api-common-protos](https://github.com/googleapis/api-common-protos/issues/75)
- [ ] [api-compiler](https://github.com/googleapis/api-compiler/issues/38)
- [ ] [code-suggester](https://github.com/googleapis/code-suggester/issues/43)
- [ ] [common-protos-java](https://github.com/googleapis/common-protos-java/issues/16)
- [ ] [common-protos-php](https://github.com/googleapis/common-protos-php/issues/12)
- [ ] [common-protos-ruby](https://github.com/googleapis/common-protos-ruby/issues/14)
- [ ] [conformance-tests](https://github.com/googleapis/conformance-tests/issues/35)
- [ ] [disco-to-proto3-converter](https://github.com/googleapis/disco-to-proto3-converter/issues/2)
- [ ] [discovery-artifact-manager](https://github.com/googleapis/discovery-artifact-manager/issues/156)
- [ ] [doc-templates](https://github.com/googleapis/doc-templates/issues/8)
- [ ] [elixir-google-api](https://github.com/googleapis/elixir-google-api/issues/5645)
- [ ] [gapic-config-validator](https://github.com/googleapis/gapic-config-validator/issues/136)
- [ ] [gapic-generator-cpp](https://github.com/googleapis/gapic-generator-cpp/issues/64)
- [ ] [gapic-generator-csharp](https://github.com/googleapis/gapic-generator-csharp/issues/268)
- [ ] [gapic-generator-dart](https://github.com/googleapis/gapic-generator-dart/issues/1)
- [ ] [gapic-generator-go](https://github.com/googleapis/gapic-generator-go/issues/418)
- [ ] [gapic-generator-java](https://github.com/googleapis/gapic-generator-java/issues/117)
- [ ] [gapic-generator-kotlin](https://github.com/googleapis/gapic-generator-kotlin/issues/49)
- [x] [gapic-generator-python](https://github.com/googleapis/gapic-generator-python/issues/538)
- [ ] [gapic-generator-ruby](https://github.com/googleapis/gapic-generator-ruby/issues/491)
- [ ] [gax-dart](https://github.com/googleapis/gax-dart/issues/1)
- [ ] [gax-dotnet](https://github.com/googleapis/gax-dotnet/issues/416)
- [ ] [gax-kotlin](https://github.com/googleapis/gax-kotlin/issues/29)
- [ ] [gax-php](https://github.com/googleapis/gax-php/issues/271)
- [ ] [gax-ruby](https://github.com/googleapis/gax-ruby/issues/230)
- [ ] [gnostic](https://github.com/googleapis/gnostic/issues/201)
- [ ] [gnostic-go-generator](https://github.com/googleapis/gnostic-go-generator/issues/20)
- [ ] [gnostic-grpc](https://github.com/googleapis/gnostic-grpc/issues/24)
- [ ] [google-api-dotnet-client](https://github.com/googleapis/google-api-dotnet-client/issues/1607)
- [ ] [google-api-go-client](https://github.com/googleapis/google-api-go-client/issues/593)
- [ ] [google-api-php-client](https://github.com/googleapis/google-api-php-client/issues/1882)
- [ ] [google-api-php-client-services](https://github.com/googleapis/google-api-php-client-services/issues/210)
- [ ] [google-api-ruby-client](https://github.com/googleapis/google-api-ruby-client/issues/892)
- [ ] [google-api-swift-client](https://github.com/googleapis/google-api-swift-client/issues/23)
- [ ] [google-auth-library-php](https://github.com/googleapis/google-auth-library-php/issues/290)
- [ ] [google-auth-library-ruby](https://github.com/googleapis/google-auth-library-ruby/issues/268)
- [ ] [google-auth-library-swift](https://github.com/googleapis/google-auth-library-swift/issues/35)
- [ ] [google-cloud-common](https://github.com/googleapis/google-cloud-common/issues/296)
- [ ] [google-cloud-cpp](https://github.com/googleapis/google-cloud-cpp/issues/4593)
- [ ] [google-cloud-dotnet](https://github.com/googleapis/google-cloud-dotnet/issues/5196)
- [ ] [google-cloud-go-testing](https://github.com/googleapis/google-cloud-go-testing/issues/37)
- [x] [google-cloud-php](https://github.com/googleapis/google-cloud-php/issues/3242)
- [ ] [google-cloud-python](https://github.com/googleapis/google-cloud-python/issues/10459)
- [ ] [google-cloud-ruby](https://github.com/googleapis/google-cloud-ruby/issues/7051)
- [ ] [google-cloudevents](https://github.com/googleapis/google-cloudevents/issues/34)
- [ ] [google-cloudevents-dotnet](https://github.com/googleapis/google-cloudevents-dotnet/issues/27)
- [ ] [google-cloudevents-go](https://github.com/googleapis/google-cloudevents-go/issues/4)
- [ ] [google-cloudevents-java](https://github.com/googleapis/google-cloudevents-java/issues/4)
- [ ] [google-cloudevents-nodejs](https://github.com/googleapis/google-cloudevents-nodejs/issues/5)
- [ ] [google-cloudevents-php](https://github.com/googleapis/google-cloudevents-php/issues/4)
- [ ] [google-cloudevents-python](https://github.com/googleapis/google-cloudevents-python/issues/3)
- [ ] [google-cloudevents-ruby](https://github.com/googleapis/google-cloudevents-ruby/issues/4)
- [ ] [googleapis.github.io](https://github.com/googleapis/googleapis.github.io/issues/37)
- [ ] [grpc-fallback-go](https://github.com/googleapis/grpc-fallback-go/issues/127)
- [ ] [jsdoc-region-tag](https://github.com/googleapis/jsdoc-region-tag/issues/18)
- [ ] [kiosk](https://github.com/googleapis/kiosk/issues/39)
- [ ] [releasetool](https://github.com/googleapis/releasetool/issues/252)
- [ ] [ruby-style](https://github.com/googleapis/ruby-style/issues/23)
- [ ] [sample-tester](https://github.com/googleapis/sample-tester/issues/149)
- [ ] [signet](https://github.com/googleapis/signet/issues/170)
- [ ] [synthtool](https://github.com/googleapis/synthtool/issues/677)
- [ ] [testing-infra-docker](https://github.com/googleapis/testing-infra-docker/issues/79)

**Comment by JustinBeckwith** [comment]
Going a different way for tracking this
